# Generated by Django 5.1.6 on 2025-07-14 11:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='Nombre')),
                ('summary', models.CharField(max_length=400, verbose_name='Descripción')),
                ('size', models.CharField(max_length=50, verbose_name='Tamaño')),
                ('materials', models.CharField(max_length=150, verbose_name='Materiales')),
                ('art_type', models.CharField(choices=[('obras-hierro', 'Obras Hierro'), ('obras-piedra-madera', 'Obras Piedra & Madera'), ('obras-madera-hierro', 'Obras Madera & Hierro')], default='obras-hierro', max_length=50, verbose_name='Tipo')),
                ('starred', models.BooleanField(default=False, verbose_name='Destacada')),
                ('image1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Imagen 1')),
                ('image2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen 2')),
                ('image3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen 3')),
                ('image4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen 4')),
                ('image5', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen 5')),
            ],
            options={
                'verbose_name': 'Obra de arte',
                'verbose_name_plural': 'Obras de arte',
            },
        ),
    ]
