# Generated by Django 5.2.4 on 2025-07-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legari_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
