# Generated by Django 5.1.6 on 2025-07-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legari_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='art_type',
            field=models.CharField(choices=[('obras-hierro', 'Obras Hierro'), ('obras-piedra-madera', 'Obras Piedra & Madera'), ('obras-madera-hierro', 'Obras Madera & Hierro')], max_length=100, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='art',
            name='materials',
            field=models.CharField(max_length=250, verbose_name='Materiales'),
        ),
        migrations.AlterField(
            model_name='art',
            name='size',
            field=models.CharField(max_length=100, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='art',
            name='summary',
            field=models.CharField(max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='art',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
    ]
