# Generated by Django 5.2.4 on 2025-07-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legari_app', '0002_art_starred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='starred',
            field=models.BooleanField(default=False, verbose_name='Destacada'),
        ),
    ]
